# Generated by Django 3.0.8 on 2020-08-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200804_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_status',
            field=models.BooleanField(default=True),
        ),
    ]
