# Generated by Django 3.0.8 on 2020-08-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200805_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='UserComment',
        ),
    ]
