# Generated by Django 3.0.8 on 2020-08-07 19:04

import auctions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200807_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[auctions.models.validate_price]),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
