# Generated by Django 3.0.8 on 2020-08-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200807_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
